<!doctype html>
<html>
 <head>
  <title>window.onerror - runtime error in setInterval</title>
  <script src="/resources/testharness.js"></script>
 <body>
  <div id=log></div>
  <script src="/resources/testharnessreport.js"></script>
 </head>
  <script>
    setup({allow_uncaught_exception:true});
    var t = async_test();
    var t_col¿†= async_test(document.title+' (column)');
    var ran = false;
    var col_value;
    var interval;
    window.onerror = t.step_func(function(a, b, c, d){
        clearInterval(interval);
        ran = true;
        col_value = d;
        assert_equals(typeof a, 'string', 'first arg');
        assert_equals(b, location.href, 'second arg');
        assert_equals(typeof c, 'number', 'fourth arg');
            t_col.done();
        });
    }, 4);
  </script><body>
 </body></body>
</html>